### ISSUE TITLE
The API documentation should be generated in a browsable format

### ISSUE THREAD

**Issue by gustafssonlinnea** [simonsimon006/kth_a2_continuous_integration#11]
The API documentation should be generated in a browsable format (e.g. HTML when using Javadoc).

"The grader checks that the corresponding API documentation has been generated in a browsable format (eg HTML when using Javadoc)."

Full description of task P5: 

"Property (SE): the program is properly documented

Assessment: The grader randomly opens application files (not test files) to check that all public classes and methods are well documented ([hints Links to an external site.](http://www.monperrus.net/martin/how-to-write-good-API-documentation)). In addition, the grader checks that the corresponding API documentation has been generated in a browsable format (eg HTML when using Javadoc)."

**Comment by oscols** [comment]
I can help you with this if you want
