### ISSUE TITLE
Document in README how to run compilation and testing

### ISSUE THREAD

**Issue by gustafssonlinnea** [simonsimon006/kth_a2_continuous_integration#4]
Property: the repository is in a valid state.

Assessment: the group or the grader checks out the repository, and runs compilation and testing through a standard way, documented in the README (in particular `mvn test`, `gradle build` or `make`).

Blocked until compilation and testing are implemented (issues #5 #6 #7, maybe more?).

**Comment by oscols** [comment]
You need java version 11or higher
